# Auto-label area:* based on changed paths.
# Labeler adds initial area hints; workflow normalization enforces final governance labels.

"area:docs":
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - README*
          - "**/README*"

"area:dr":
  - changed-files:
      - any-glob-to-any-file:
          - scripts/ops/**
          - ops/**

"area:release":
  - changed-files:
      - any-glob-to-any-file: scripts/release/**

"area:infra":
  - changed-files:
      - any-glob-to-any-file:
          - ops/aws/**
          - ops/k8s/**
          - ops/launchd/**

"area:providers":
  - changed-files:
      - any-glob-to-any-file: src/ji_engine/providers/**

"area:engine":
  - changed-files:
      - any-glob-to-any-file:
          - src/ji_engine/**
          - src/jobintel/**
          - scripts/run_daily.py
